elearning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("home/", include("home.urls")),
    path("search/", include("search.urls")),
    path("course/", include("courses.urls")),
    path("status-updates/", include("status_updates.urls")),
    path("feedback/", include("feedback.urls")),
    path("notifications/", include("notifications.urls")),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("<str:username>/", views.home, name="home"),
]

status_updates/urls.py
from django.urls import path
from . import views

app_name = "status_updates"

urlpatterns = [
    path("create/", views.create_status_update_view, name="create_status_update"),
    path(
        "delete/<int:id>/",
        views.delete_status_update_view,
        name="delete_status_update",
    ),
]

status_updates/models.py
from django.db import models
from django.conf import settings


class StatusUpdate(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="status_updates",
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

status_updates/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .models import StatusUpdate


@login_required
def create_status_update_view(request):
    # Get the content from the request
    content = request.POST.get("content")

    # If the content is not empty
    if content:
        # Create a status update
        StatusUpdate.objects.create(user=request.user, content=content)
        messages.success(request, "Status update posted successfully")
    else:
        # Else, send error message
        messages.error(request, "Please enter a status update")

    # If the user is a student
    if request.user.role == request.user.Role.STUDENT:
        # Redirect to the student dashboard with the updated status updates
        return redirect("dashboard:student")
    # If the user is a teacher
    if request.user.role == request.user.Role.TEACHER:
        # Redirect to the teacher dashboard with the updated status updates
        return redirect("dashboard:teacher")


@login_required
def delete_status_update_view(request, id):
    # Get the status update
    status_update = StatusUpdate.objects.get(id=id)

    # Delete the status update
    status_update.delete()
    messages.success(request, "Status update deleted successfully")

    # If the user is a student
    if request.user.role == request.user.Role.STUDENT:
        # Redirect to the student dashboard with the updated status updates
        return redirect("dashboard:student")
    # If the user is a teacher
    if request.user.role == request.user.Role.TEACHER:
        # Redirect to the teacher dashboard with the updated status updates
        return redirect("dashboard:teacher")

status_updates/templates/status_updates/status_updates.html
<div class="rounded-lg border border-stone-700 bg-stone-950">
  <h2 class="px-6 pt-6 text-lg font-semibold">Status Updates</h2>
  <!-- Create Form -->
  <form
    method="POST"
    action="{% url 'status_updates:create_status_update' %}"
    class="space-y-4 border-b-[1px] border-stone-700 p-6"
  >
    {% csrf_token %}
    <div class="flex gap-4">
      <!-- User Avatar -->
      <img
        src="{% if request.user.profile_picture %}{{ request.user.profile_picture.url }}{% else %}https://ui-avatars.com/api/?name={{ request.user.first_name }}+{{ request.user.last_name }}{% endif %}"
        alt="Profile Picture"
        class="h-12 w-12 rounded-full object-cover"
      />

      <!-- Status Input -->
      <div class="mt-2 flex-1">
        <label for="content"></label>
        <textarea
          name="content"
          id="content"
          rows="3"
          class="w-full placeholder:text-stone-400 focus:outline-none"
          placeholder="What is happening?!"
        ></textarea>
      </div>
    </div>

    <!-- Post Button -->
    <div class="flex justify-end">
      <button
        type="submit"
        class="cursor-pointer rounded-lg bg-stone-50 px-6 py-2 text-sm font-medium text-stone-950 transition-colors hover:bg-stone-200"
      >
        Post
      </button>
    </div>
  </form>

  <!-- Status Updates List -->
  <div class="divide-y divide-stone-800">
    {% for status_update in status_updates %}
    <div class="p-6">
      <!-- User Full Name, Username -->
      <div class="mb-2 flex items-center justify-between">
        <div>
          <span class="font-medium"
            >{{ status_update.user.get_full_name }}</span
          >
          <span class="text-sm text-stone-400"
            >@{{ status_update.user.username }}</span
          >
        </div>

        <!-- Delete Button -->
        <form
          method="POST"
          action="{% url 'status_updates:delete_status_update' status_update.id %}"
        >
          {% csrf_token %}
          <button
            type="submit"
            class="flex cursor-pointer items-center transition-colors hover:text-stone-400"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="lucide lucide-trash-2"
            >
              <path d="M3 6h18" />
              <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
              <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
              <line x1="10" x2="10" y1="11" y2="17" />
              <line x1="14" x2="14" y1="11" y2="17" />
            </svg>
          </button>
        </form>
      </div>

      <!-- Content -->
      <p class="mb-2">{{ status_update.content }}</p>

      <!-- Timestamp -->
      <span class="text-sm text-stone-400">
        {{ status_update.created_at|timesince }} ago
      </span>
    </div>
    {% empty %}
    <div class="p-6">
      <!-- No Status Updates -->
      <p class="text-center text-stone-400">No status updates</p>
    </div>
    {% endfor %}
  </div>
</div>