elearning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("home/", include("home.urls")),
    path("search/", include("search.urls")),
    path("course/", include("courses.urls")),
    path("status-updates/", include("status_updates.urls")),
    path("feedback/", include("feedback.urls")),
    path("notifications/", include("notifications.urls")),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("<str:username>/", views.home, name="home"),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.search_view, name='search'),
] 

search/views.py
from django.shortcuts import render
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required


@login_required
def search_view(request):
    # Get the query from the request
    query = request.GET.get("query", "")
    # Store the results
    results = []

    # If the query is not empty
    if query:
        # Get the user model
        User = get_user_model()
        # Search for users
        users = User.objects.filter(
            Q(username__icontains=query)
            | Q(first_name__icontains=query)
            | Q(last_name__icontains=query)
        )[:5]

        # Format user results
        for user in users:
            results.append(
                {
                    "name": user.get_full_name(),
                    "username": user.username,
                    "role": user.role.capitalize(),
                }
            )

        # Render the search results
        return render(
            request, "search/search_results.html", {"results": results, "query": query}
        )

search/templates/search/search_bar.html
<div class="relative">
  <!-- Search Bar and Search Icon -->
  <div class="flex items-center">
    <!-- Use htmx to search for users -->
    <!-- Search query is triggered on keyup after 300ms of inactivity -->
    <!-- Search results are displayed in the searchResults div -->
    <input
      type="text"
      name="query"
      placeholder="Search"
      hx-get="{% url 'search:search' %}"
      hx-trigger="keyup changed delay:300ms"
      hx-target="#searchResults"
      class="w-64 rounded-lg border border-stone-700 bg-stone-950 px-3 py-2 text-sm transition-colors outline-none focus:border-stone-50"
    />
    <button class="absolute right-3 text-stone-400">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <circle cx="11" cy="11" r="8" />
        <line x1="21" y1="21" x2="16.65" y2="16.65" />
      </svg>
    </button>
  </div>

  <!-- Search Results -->
  <div
    id="searchResults"
    class="absolute mt-2 max-h-64 w-64 overflow-y-auto rounded-lg border border-stone-800 bg-stone-950"
  ></div>
</div>

search/templates/search/search_results.html
{% if results %} {% for result in results %}
<!-- Search Result -->
<a
  href="/home/{{ result.username }}/"
  class="block px-3 py-2 transition-colors hover:bg-stone-900"
>
  <!-- Search Result Name -->
  <div class="mb-2 text-sm">{{ result.name }}</div>
  <!-- Search Result Role -->
  <div class="text-xs text-stone-400">{{ result.role }}</div>
</a>
{% endfor %} {% else %} {% if query %}
<!-- No users found -->
<div class="px-3 py-2 text-center text-sm text-stone-400">No users found</div>
{% endif %} {% endif %}